
# VARIABLES

CC = g++
CFLAGS = -Wall -g
LDFLAGS = -lstdc++
TARGET = day-2

# RULES

all: $(TARGET)

$(TARGET): day-2.cpp
	$(CC) $(CFLAGS) -o $(TARGET) day-2.cpp $(LDFLAGS)

clean:
	rm -f $(TARGET)

.PHONY: all-clean
